CREATE TABLE IF NOT EXISTS user (
  id INT AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(255) NOT NULL UNIQUE,
  name VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  phone VARCHAR(20) NOT NULL,
  birthDate DATE NOT NULL,
  statusId INT NOT NULL,
  roleId INT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS profile (
  id INT AUTO_INCREMENT PRIMARY KEY,
  unitSystem ENUM('metric', 'imperial') NOT NULL,
  gender ENUM('male', 'female') NOT NULL,
  weight FLOAT NOT NULL CHECK (weight BETWEEN 30 AND 1000),
  height FLOAT NOT NULL CHECK (height BETWEEN 30 AND 250),
  age INT NOT NULL CHECK (age BETWEEN 18 AND 150),
  waist FLOAT NOT NULL CHECK (waist BETWEEN 15 AND 200),
  neck FLOAT NOT NULL CHECK (neck BETWEEN 8 AND 80),
  hip FLOAT NULL CHECK (hip BETWEEN 15 AND 200),
  userId INT NOT NULL UNIQUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_profile_user FOREIGN KEY (userId) REFERENCES user(id) ON DELETE CASCADE
);
